object Version {
  val APP           = "0.0.1-SNAPSHOT"
  val SCALA         = "2.11.7"
  val LOGBACK       = "1.1.7"
  val MYSQLCONN     = "5.1.36"
  val CUCUMBER      = "1.2.5"
  val JACKSON       = "2.8.5"
  val JACKSONMODULE = "2.6.1"
  val JUNIT         = "4.12"
  val GUICE         = "4.1.0"
  val JAXRS         = "3.0.12.Final"
  val JAVAEE        = "7.0"
  val HIBERNATE     = "5.2.5.Final"
  val H2            = "1.4.193"
  val SELENIUM      = "3.0.1"
  val PLAYMAILER    = "5.0.0"
  val JJWT          = "0.7.0"
  val COMMONS_IO    = "2.5"
}
